--[[--
Icon picker categories. A category lists the glyphs in `names`, then those
whose name starts with each of `prefixes` in turn, so put the likeliest first.
]]

local _ = require("gettext")

return {
    {
        key = "reading",
        title = _("Reading"),
        prefixes = {
            "book",
            "library",
            "table-of-contents",
            "translate",
            "dictionary",
            "magnify",
            "note",
            "pencil",
            "format-quote",
            "quote",
            "read",
            "glasses",
            "newspaper",
            "eye",
            "text-to-speech",
            "file-document",
            "label",
            "tag",
            "feather",
            "comment",
        },
        names = { "search", "search.1", "list", "list-ordered", "list-unordered", "list_alt" },
    },
    {
        key = "layout",
        title = _("Text and layout"),
        prefixes = {
            "format-",
            "font",
            "text",
            "view-",
            "page-layout",
            "fullscreen",
            "rotate",
            "screen-rotation",
            "crop",
            "zoom",
            "align",
            "indent",
            "contrast",
            "invert-colors",
            "image",
            "border",
        },
    },
    {
        key = "navigation",
        title = _("Navigation"),
        prefixes = {
            "home",
            "undo",
            "redo",
            "history",
            "exit",
            "logout",
            "login",
            "chevron",
            "skip-",
            "page-first",
            "page-last",
            "fast-forward",
            "rewind",
            "step-",
            "menu",
            "dots-",
            "apps",
            "map-marker",
            "compass",
            "navigation",
            "swap-",
            "launch",
            "open-in",
            "sign-",
            "reply",
            "share",
            "arrow",
        },
    },
    {
        key = "device",
        title = _("Device"),
        prefixes = {
            "power",
            "sleep",
            "restart",
            "wifi",
            "bluetooth",
            "brightness",
            "lightbulb",
            "weather-night",
            "weather-sunny",
            "moon",
            "sun",
            "theme-light-dark",
            "white-balance",
            "cog",
            "settings",
            "tune",
            "wrench",
            "lock",
            "sync",
            "refresh",
            "reload",
            "update",
            "cloud",
            "download",
            "upload",
            "signal",
            "access-point",
            "network",
            "volume",
            "headphones",
            "flashlight",
            "candle",
            "screenshot",
            "camera",
            "cellphone",
            "tablet",
            "monitor",
            "laptop",
            "keyboard",
            "usb",
            "memory",
            "bug",
            "terminal",
            "console",
            "battery",
        },
    },
    {
        key = "files",
        title = _("Files"),
        prefixes = {
            "folder",
            "file",
            "archive",
            "content-",
            "delete",
            "trash",
            "clipboard",
            "sort",
            "filter",
            "database",
            "harddisk",
            "hdd",
            "sd",
            "save",
            "inbox",
            "package",
            "rss",
            "email",
            "link",
            "server",
            "web",
            "earth",
            "globe",
        },
    },
    {
        key = "time",
        title = _("Time"),
        prefixes = { "clock", "alarm", "calendar", "timer", "watch", "av-timer", "speedometer" },
    },
    {
        key = "symbols",
        title = _("Symbols"),
        prefixes = {
            "star",
            "heart",
            "check",
            "close",
            "plus",
            "minus",
            "alert",
            "information",
            "help",
            "flag",
            "bell",
            "emoticon",
            "account",
            "puzzle",
            "flash",
            "fire",
            "music",
            "play",
            "pause",
            "stop",
            "circle",
            "square",
            "checkbox",
            "radiobox",
            "toggle-switch",
            "thumb",
            "trophy",
            "gift",
            "coffee",
            "pin",
            "paperclip",
            "key",
            "shield",
            "infinity",
            "chess",
            "dice",
            "gamepad",
            "cards",
            "cat",
            "paw",
            "leaf",
            "flower",
            "tree",
            "anchor",
            "rocket",
        },
    },
}
