"""Writes minimenu/icons/glyphs.lua from KOReader's bundled symbols font.

    mise exec uv@latest -- uv run --no-project --with fonttools \
        python tools/gen_glyphs.py <koreader>/resources/fonts/nerdfonts/symbols.ttf

Names come from the font's own cmap: upstream Nerd Font name lists disagree
with the glyphs KOReader actually ships.
"""

import hashlib
import pathlib
import re
import sys

from fontTools.ttLib import TTFont

# Pomicons (U+E0xx) and Seti/Devicons brand logos (U+E5xx-U+E6xx) are left out.
RANGES = [(0xE200, 0xE4FF), (0xE700, 0xF8FF)]

OUT = pathlib.Path(__file__).resolve().parent.parent / "minimenu" / "icons" / "glyphs.lua"


def display_name(name, cp):
    # Some Font Awesome glyphs carry placeholder names like "_279" or "uniF000".
    if re.fullmatch(r"_\d+|uni[0-9A-F]{4,6}", name):
        return f"u+{cp:04x}"
    return name


def main(font_path):
    data = pathlib.Path(font_path).read_bytes()
    cmap = TTFont(font_path).getBestCmap()
    entries = sorted(
        ((display_name(name, cp), cp) for cp, name in cmap.items() if any(lo <= cp <= hi for lo, hi in RANGES)),
        key=lambda e: (e[0].startswith("u+"), e[0].lower(), e[1]),
    )
    lines = [
        "-- Generated by tools/gen_glyphs.py; do not edit.",
        f"-- symbols.ttf sha256 {hashlib.sha256(data).hexdigest()[:16]}, {len(entries)} glyphs.",
        "",
        "return {",
    ]
    lines += [f'    {{ "{name}", 0x{cp:04X} }},' for name, cp in entries]
    lines += ["}", ""]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {len(entries)} glyphs to {OUT}")


if __name__ == "__main__":
    main(sys.argv[1])
